version: 2.1

parameters:
  version:
    type: string
    default: 1.1.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    parameters:
      cluster:
        description: cluster environment
        type: string
        default: << pipeline.parameters.version >>
      - checkout
      - run:
          name: Say hello in << parameters.cluster >>
          command: echo 'Hello, World! << parameters.cluster >>'
      - run:
          name: ceshi pipeline parameters
          command: |
            echo << pipeline.parameters.version >>


workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  say-hello-workflow2:
    jobs:
      - say-hello:
          cluster: 传入参数

